### ISSUE TITLE
Raise notification after $x amount of time above threshold

### ISSUE THREAD

**Issue by nradonicich** [scobal/seyren#247]
Instead of raising a notification/subscription right away when the value returned is above threshold it would be nice to set a timer value that the notification/subscription will be sent if the monitored value is above the thresholds for x amount of time.

SEND TO SUBSCRIPTION IF (value > 100 AND inAlarm > 15 minutes)

If that makes any sense.

**Comment by paulcgt** [comment]
The movingAverage() function can achieve what you need - well, more or less. The problem with it though is that you'd use a target that looks something like this: movingAverage(pending_transactions.gauge,20) > 95 

In the alert sent to your subscriptions you'd get the metric value as something like 95.7943228, which can be a bit confusing to whoever's on standby because they may wonder how there could be 95.7943228 pending transactions.

**Comment by slogar** [comment]
If I put movingAverage function in alerts i get always UNKOWN. It's also true that i am doing moving average for last hour and half. Are there any extra limits?

**Comment by neilprosser** [comment]
@slogar I think that problem can be mitigated by setting a suitable `from` value on your check from the UI.
