### ISSUE TITLE
Is seyren abandonware?

### ISSUE THREAD

**Issue by jrgifford** [scobal/seyren#258]
Hi! Is seyren abandonware? There hasn't been much activity lately, and there are several issues that haven't been touched at all.

**Comment by neilprosser** [comment]
Hi @jrgifford, it certainly isn't from my point of view. You're right though, it has been a bit quiet recently. I've been busy with other things so haven't been dedicating as much time to it as I used to. We invited @obazoud on as a committer last year to spread the load a bit more since he was more actively developing Seyren.

We're still using it in production at MixRadio but ours is the original use-case (Graphite alerting based on MongoDB storage) so it's definitely not going anywhere.

**Comment by obazoud** [comment]
I think you had an answer.
