### ISSUE TITLE
expose createAlert in API

### ISSUE THREAD

**Issue by jozic** [scobal/seyren#416]
it possible to get alerts and delete alerts via api, but not create

Could you please add an endpoint for creating alerts?
Thanks

**Comment by TyBrown** [comment]
I feel like this is by design... Alerts get created by Seyren itself when a metric in a check exceeds the thresholds of the check.

The choice to allow for getting Alerts via the API makes sense, as does deleting them since some people like to keep their Seyren consoles cleaned up and old alerts on a check can be messy. However, I'm not sure that creating an Alert via the API makes sense.

**Comment by jozic** [comment]
@TyBrown thank you!
for some reason I mixed it up with subscription, which can e created via api.
closing
